package com.springboot.laptop.model.dto;

public enum ErrorCode {
    DELETE_PRODUCT_ERROR, FIND_PRODUCT_ERROR, FIND_CATEGORY_ERROR, DELETE_CATEGORY_ERROR, ADD_CATEGORY_ERROR, DUPLICATED_DATA, ADD_BRAND_ERROR, NOT_FOUND_EXCEPTION
}
