CREATE TABLE address (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   user_id BIGINT,
   address VARCHAR(255),
   city VARCHAR(255),
   country VARCHAR(255),
   zipcode VARCHAR(255),
   phone_number VARCHAR(255) NOT NULL,
   CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   title VARCHAR(255) NOT NULL,
   content VARCHAR(255),
   user_id BIGINT,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   badge_id BIGINT,
   CONSTRAINT pk_articles PRIMARY KEY (id)
);

CREATE TABLE badges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255) NOT NULL,
   description VARCHAR(255),
   CONSTRAINT pk_badges PRIMARY KEY (id)
);

CREATE TABLE brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   CONSTRAINT pk_brands PRIMARY KEY (id)
);

CREATE TABLE cart_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   quantity BIGINT,
   cart_id BIGINT,
   product_id BIGINT,
   CONSTRAINT pk_cart_detail PRIMARY KEY (id)
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   category_name VARCHAR(255) NOT NULL,
   enabled BOOLEAN,
   image_url VARCHAR(255),
   CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE categories_brands (
  brand_id BIGINT NOT NULL,
   category_id BIGINT NOT NULL
);

CREATE TABLE order_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   order_id BIGINT,
   product_id BIGINT,
   quantity BIGINT,
   total FLOAT NOT NULL,
   CONSTRAINT pk_order_detail PRIMARY KEY (id)
);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   user_id BIGINT,
   order_date date,
   total FLOAT NOT NULL,
   order_status VARCHAR(255),
   address_id BIGINT,
   payment_method VARCHAR(255),
   CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE post_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   image_url VARCHAR(255),
   post_id BIGINT,
   CONSTRAINT pk_post_images PRIMARY KEY (id)
);

CREATE TABLE product_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   value VARCHAR(255) NOT NULL,
   product_id BIGINT,
   CONSTRAINT pk_product_details PRIMARY KEY (id)
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   primary_image VARCHAR(255),
   enabled BOOLEAN NOT NULL,
   original_price FLOAT,
   discount_percent FLOAT,
   brand_id BIGINT,
   description VARCHAR(255),
   in_stock BOOLEAN,
   category_id BIGINT,
   product_qty BIGINT,
   CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE reset_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   token VARCHAR(255),
   user_id BIGINT,
   active BOOLEAN,
   created_date TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_reset_token PRIMARY KEY (id)
);

CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   headline VARCHAR(128) NOT NULL,
   comment VARCHAR(300) NOT NULL,
   rating INTEGER NOT NULL,
   votes INTEGER NOT NULL,
   review_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   product_id BIGINT,
   customer_id BIGINT,
   CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   description VARCHAR(255),
   CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE user_cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   user_id BIGINT,
   CONSTRAINT pk_user_cart PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_timestamp TIMESTAMP WITHOUT TIME ZONE,
   modified_timestamp TIMESTAMP WITHOUT TIME ZONE,
   username VARCHAR(255),
   password VARCHAR(255),
   email VARCHAR(255),
   name VARCHAR(255),
   phone_number VARCHAR(255),
   imgurl VARCHAR(255),
   enabled BOOLEAN,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_role (
  role_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL
);

ALTER TABLE address ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE articles ADD CONSTRAINT FK_ARTICLES_ON_BADGE FOREIGN KEY (badge_id) REFERENCES badges (id);

ALTER TABLE articles ADD CONSTRAINT FK_ARTICLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE cart_detail ADD CONSTRAINT FK_CART_DETAIL_ON_CART FOREIGN KEY (cart_id) REFERENCES user_cart (id);

ALTER TABLE cart_detail ADD CONSTRAINT FK_CART_DETAIL_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_detail ADD CONSTRAINT FK_ORDER_DETAIL_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_detail ADD CONSTRAINT FK_ORDER_DETAIL_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE post_images ADD CONSTRAINT FK_POST_IMAGES_ON_POST FOREIGN KEY (post_id) REFERENCES articles (id);

ALTER TABLE products ADD CONSTRAINT FK_PRODUCTS_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brands (id);

ALTER TABLE products ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE product_details ADD CONSTRAINT FK_PRODUCT_DETAILS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE reset_token ADD CONSTRAINT FK_RESET_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reviews ADD CONSTRAINT FK_REVIEWS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE reviews ADD CONSTRAINT FK_REVIEWS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE user_cart ADD CONSTRAINT FK_USER_CART_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE categories_brands ADD CONSTRAINT fk_catbra_on_brand_entity FOREIGN KEY (brand_id) REFERENCES brands (id);

ALTER TABLE categories_brands ADD CONSTRAINT fk_catbra_on_category_entity FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE users_role ADD CONSTRAINT fk_userol_on_user_entity FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_role ADD CONSTRAINT fk_userol_on_user_role_entity FOREIGN KEY (role_id) REFERENCES role (id);